name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Jekyll site using Docker
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/vendor/bundle:/usr/local/bundle \
        jekyll/jekyll:latest \
        jekyll build

    - name: Upload Jekyll site to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to web server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER: ${{ secrets.SERVER }}
        USER: ${{ secrets.USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        ssh-keyscan -H $SERVER >> ~/.ssh/known_hosts
        rsync -avz --delete _site/ $USER@$SERVER:/var/www/html/
