name: HTML, CSS, and JavaScript Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint HTML
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run ESLint
        run: |
          npx eslint .
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      
        
