name: Docker CI Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to DockerHub (optional if you want to push to DockerHub)
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t your-docker-image-name:latest .

    # Run the Docker container for testing
    - name: Run Docker container
      run: docker run -d -p 8080:8080 your-docker-image-name:latest

    # Optionally, push the Docker image to DockerHub
    - name: Push Docker image to DockerHub
      run: docker push your-docker-image-name:latest

    # Stop and remove the container after testing (optional)
    - name: Stop and remove Docker container
      run: docker stop $(docker ps -q) && docker rm $(docker ps -a -q)
