name: Docker CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Docker if not already available
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    # Ensure Docker is running
    - name: Start Docker service
      run: sudo systemctl start docker

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t your-docker-image-name:latest .

    # Run the Docker container for testing
    - name: Run Docker container
      run: docker run -d --name test-container -p 8080:8080 your-docker-image-name:latest

    # Verify the container is running
    - name: Verify container status
      run: docker ps -a

    # Optionally, push the Docker image to DockerHub (if desired)
    - name: Log in to DockerHub
      if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to DockerHub
      if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
      run: docker push your-docker-image-name:latest

    # Stop and remove the container after testing
    - name: Stop and remove Docker container
      run: |
        docker stop test-container
        docker rm test-container
