name: CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx (if needed for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to the Docker registry (optional)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t my-app:latest .

    # Run the Docker container
    - name: Run Docker container
      run: docker run --name my-app-container -d my-app:latest

    # Run tests inside the Docker container (replace with your test command)
    - name: Run tests
      run: docker exec my-app-container ./run-tests.sh

    # Stop and remove the Docker container after tests
    - name: Stop and remove container
      run: docker rm -f my-app-container

    # Push the Docker image to Docker Hub (optional)
    - name: Push Docker image
      run: docker push my-app:latest
      if: github.event_name == 'push'
