name: CI Workflow

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run in the workflow
jobs:
  lint:
    # Define the environment to run the job
    runs-on: ubuntu-latest

    # Steps for the linting job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: |
          npx eslint .    # For JavaScript
          npx stylelint "**/*.css"    # For CSS

  build:
    # Define the environment to run the job
    runs-on: ubuntu-latest

    # Steps for the build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  deploy:
    # Define the environment to run the job
    runs-on: ubuntu-latest
    needs: build  # Only run after the build job is successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Directory containing the built files
